config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :businesses do
    resources :resources
    resources :agreements
  end
  resources :users do
    resources :businesses
    resources :resources
    resources :agreements
  end
  resources :resources do
    resources :agreements
  end
  root to: 'welcome#index'
  get ':format', to: 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: %i[show edit update destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    # @businesses = current_user.business.includes(resource: [:agreements])
    @businesses = current_user.businesses.includes(:resources)
  end

  def show
  end

  def new
    @business = Business.new
  end

  def edit
    @business = Business.find(params[:id])
  end

  def create
    @business = current_user.businesses.create(business_params)
    if @business.errors.any?
      flash[:alert] = "Something went wrong."
      render :new
    else
      flash[:success] = "#{@business.name} successfully created!"
      redirect_to businesses_path
    end
  end

  def update
    @business = current_user.businesses.find(params[:id]).update(business_params)
    redirect_to businesses_path
  end

  def destroy
    @business = current_user.businesses.find(params[:id]).destroy
    redirect_to businesses_path
  end

  private

  def business_params
    params.require(:business).permit(
      :name,
      :url,
      :location,
      :description
    )
  end

  def set_business
    @business = Business.find(params[:id])
  end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/views/businesses/_business_form.html.erb
<div class="home-column-surface">
  <%= form_with model: @business, local: true do |form| %>
      <div class="form-input">
        <%= form.label :name %>
        <%= form.text_field :name, placeholder: "Whomst'd've ventures, Pty Ltd.", size: 55 %>
      </div>
      <div class="form-input">
        <%= form.label :url %>
        <%= form.text_field :url, placeholder: "www.toebeans.com.au", size: 55 %>
      </div>
      <div class="form-input">
        <%= form.label :location %>
        <%= form.text_field :location, placeholder: "420 Fake street, Suburbia, VIC, 90210", size: 55 %>
      </div>
      <div class="form-input">
        <%= form.label :description %>
        <%= form.text_area :description, placeholder: "We print fanzines here. And make money.", cols: 50, rows: 10 %>
      </div>
      
      <div class="form-input">
        <%= form.submit %>
      </div>
  <% end %>
</div>

app/views/businesses/_business_list.html.erb
<div class="home-column-panel">
  <ul>
    <h1>
      <%= biz.name %>
    </h1>
    <h2 class="wrap-text">
      <%= link_to biz.url, clean_url(biz.url), target: "_blank" %>
    </h2>
    <li class="wrap-text">
      <%= "Address: #{biz.location}" %>
    </li>
    <li>
      <%= "lat: #{biz.latitude}, lon: #{biz.longitude}" %>
    </li>
    <li class="wrap-text">
      <%= biz.description %>
    </li>
    <p>
      <%= link_to 'View business', business_path(biz.id), class: "inlinebutton" %>
      <%= link_to 'Edit business', edit_business_path(biz), class: "inlinebutton" %>
      <%= link_to "Delete business", business_path(biz.id), method: :delete, data: { confirm: "This will delete #{biz.name} and all associated resources. Are you sure?" }, class: "inlinebutton" %>
    </p>
    </ul>
</div>

app/views/businesses/create.html.erb
<h1>Businesses#create</h1>
<p>Find me in app/views/businesses/create.html.erb</p>

app/views/businesses/destroy.html.erb
<h1>Businesses#destroy</h1>
<p>Find me in app/views/businesses/destroy.html.erb</p>

app/views/businesses/edit.html.erb
<%= render 'shared/navbar' %>
<div class="home-column">
  <div class="home-column-panel">
    <h1>Edit a business</h1>
    <%= render 'business_form', business: @business %>
  </div>
</div>

app/views/businesses/index.html.erb
<%= render 'shared/navbar' %>
<div class="home-column">
  <% if @businesses %>
    <% @businesses.each do |biz| %>
      <%= render partial: 'business_list', locals: {biz: biz} %>
    <% end %>
  <% end %>
  <div class="home-column-panel">
    <%= link_to "New business", new_business_path, class: "home-column-surface" %>
  </div>
</div>

app/views/businesses/new.html.erb
<div class="home-column">
  <div class="home-column-panel">
    <h1>Add a new business</h1>
    <%= render 'business_form', business: @business %>
  </div>
</div>

app/views/businesses/show.html.erb
<%= render 'shared/navbar' %>
<div class="home-column">
  <% if @business %>
    <%= render partial: 'business_list', locals: {biz: @business} %>
    <% @business.resources.each do |resource| %>
      <%= render partial: 'resources/resource_list', locals: {resource: resource, business: @business, divclass: "home-column-surface"} %>
    <% end %>
  <% end %>
  <div class="home-column-panel">
    <%= link_to "New business", new_business_path, class: "home-column-surface" %>
  </div>
</div>

app/views/businesses/update.html.erb
<h1>Businesses#update</h1>
<p>Find me in app/views/businesses/update.html.erb</p>