config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :businesses do
    resources :resources
    resources :agreements
  end
  resources :users do
    resources :businesses
    resources :resources
    resources :agreements
  end
  resources :resources do
    resources :agreements
  end
  root to: 'welcome#index'
  get ':format', to: 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_logo.html.erb
<%= image_tag("logo.svg", style: "max-width: 25vw; max-height: 25vh; display: inline-block; filter: drop-shadow( 2px 2px 2px #00000080);") %>

app/views/shared/_navbar.html.erb
<nav class="nav">
  <ul>
    <li>
      <div class="homebutton">
        <%= link_to image_tag("logo.svg", class: "logo tooltip"), root_path %>
      </div>
    </li>
    <li class="hideable">
      <%= link_to "Home", root_path %>
    </li>
    <li>
      <%= link_to image_tag("icons/browse-all.svg", class: "icon tooltip"), resources_path %>
      <%= link_to "Browse resources for hire", resources_path, class: "text" %>
    </li>
    <% if user_signed_in? %>
      <li>
        <%= link_to image_tag("icons/browse-mine.svg", class: "icon tooltip"), user_resources_path(current_user) %>
        <%= link_to "My resources", user_resources_path(current_user), class: "text" %>
      </li>
      <li>
        <%= link_to image_tag("icons/agreement.svg", class: "icon tooltip"), user_agreements_path(current_user) %>
        <%= link_to "My agreements", user_agreements_path(current_user), class: "text" %>
      </li>
      <li class="righthand">
        <%= link_to image_tag("icons/factory.svg", class: "icon tooltip"), businesses_path %>
        <%= link_to "Businesses", businesses_path, class: "text" %>
      </li>
      <li>
        <%= link_to image_tag("icons/logout.svg", class: "icon tooltip"), destroy_user_session_path, method: :delete %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "text" %>
      </li>
    <% else %>
      <li class="righthand">
        <%= link_to image_tag("icons/login.svg", class: "icon tooltip"), new_user_session_path %>
        <%= link_to "Login", new_user_session_path, class: "text" %>
      </li>
    <% end %>
  </ul>
</nav>