config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :businesses do
    resources :resources
    resources :agreements
  end
  resources :users do
    resources :businesses
    resources :resources
    resources :agreements
  end
  resources :resources do
    resources :agreements
  end
  root to: 'welcome#index'
  get ':format', to: 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/resources/_resource_form.html.erb
<div class="home-column-surface">
  <%= form_with model: [ @business, @resource ], local: true do |form| %>
      <div class="form-input">
        <%= form.label :name %>
        <%= form.text_field :name, placeholder: "Office space, 12sqm in Brunswick", size: 55 %>
      </div>
      <div class="form-input">
        <%= form.label :description %>
        <%= form.text_area :description, placeholder: "busy northside workspace has a spare side office in it's own 4x3m room with aircon, power, a phone and a desk already installed.", cols: 50, rows: 10 %>
      </div>
      <div class="form-input">
        <%= form.label :picture %>
        <%= form.file_field :picture, accept: 'image/png,image/gif,image/jpeg,image/jpg,image/svg+xml,image/webp' %>
        <%#= form.label "or enter a direct URL of a picture" %>
        <%#= form.text_field :picture, placeholder: "www.toebeans.com.au/my_cat.jpg", size: 55 %>
      </div>
      <%= form.hidden_field :business_id, value: @business.id %>
      <%= form.hidden_field :user_id, value: @user.id %>
      <div class="form-input">
        <%= form.submit %>
      </div>
  <% end %>
</div>

app/views/resources/_resource_list.html.erb
<%= tag.div class: (divclass || "") do %>
  <h1>
    <%= resource.name %>
  </h1>
  <h3 class="wrap-text">
    <%= "#{business.suburb}, #{business.county}" %>
  </h3>
  <p class="wrap-text">
    <%= "Description: #{resource.description}" %>
  </p>
  <%= image_tag resource.picture if resource.picture.attached? %>
  <ul class="inline-list">
    <li><%= link_to 'View', resource_path(resource), class: "inlinebutton" %></li>
    <%# if can? :edit, resource %>
    <% if @current_userid == business.user_id %>
      <% puts "user can edit this resource" %>
      <li><%= link_to 'Edit', edit_business_resource_path(business,resource), class: "inlinebutton" %></li>
      <li class="righthand"><%= link_to "Delete", resource_path(resource), method: :delete, data: { confirm: "This will delete #{resource.name} and all associated agreements. Are you sure?" }, class: "inlinebutton" %></li>
    <% else %>
      <% puts "user cannot edit this resource" %>
      <li class="righthand"><%= link_to "I'm interested!", new_resource_agreement_path(resource), class: "inlinebutton" %>
    <% end %>
  </ul>
<% end %>

app/views/resources/create.html.erb
<h1>Resources#create</h1>
<p>Find me in app/views/resources/create.html.erb</p>

app/views/resources/destroy.html.erb
<h1>Resources#destroy</h1>
<p>Find me in app/views/resources/destroy.html.erb</p>

app/views/resources/edit.html.erb
<%= render 'shared/navbar' %>
<div class="home-column">
  <div class="home-column-panel">
    <h1>Edit resource for hire.</h1>
    <h2><%= "#{@business.name}" %></h2>
    <%= render partial: 'resource_form', locals: {business: @business, resource: @resource} %>
  </div>
</div>

app/views/resources/index.html.erb
<%= render 'shared/navbar' %>
<% if @businesses.all.count > 0 %>
  <% if @current_userid == 0 %>
    <div class="home-column-inset">
      <% @businesses.each do |b| %>
        <% b.resources.each do |resource| %>
          <%= render partial: 'resource_list', locals: {resource: resource, business: b, divclass: "home-column-panel"} %>
        <% end %>
      <% end %>
    </div>
  <% else %>
    <div class="home-column-inset">
      <% @businesses.each do |b| %>
        <% b.resources.each do |resource| %>
          <%= render partial: 'resource_list', locals: {resource: resource, business: b, divclass: "home-column-panel"} %>
        <% end %>
        <% if @current_userid == b.user_id %>
          <div class="home-column-inset full-width-panel">
            <%= link_to "New resource for #{b.name}", new_business_resource_path(b), class: "home-column-surface" %>
          </div>
        <% end %>
      <% end %>
    </div>
  <% end %>
<% else %>
  <div class="display">
  <h2>You need to have a business to have resources. Click "Businesses" or the Factory icon to add one!</h2>
  </div>  
<% end %>

app/views/resources/new.html.erb
<%= render 'shared/navbar' %>
<div class="home-column">
  <div class="home-column-panel">
    <h1>Add a new resource for hire.</h1>
    <h2><%= "#{@business.name}" %></h2>
    <%= render partial: 'resource_form', locals: {business: @business, resource: @resource, user: @user} %>
  </div>
</div>

app/views/resources/show.html.erb
<%= render 'shared/navbar' %>
<div class="home-column">
  <%= render partial: 'resource_list', locals: {resource: @resource, business: @business, divclass: "home-column-panel full-width-panel"} %>
</div>

app/views/resources/update.html.erb
<h1>Resources#update</h1>
<p>Find me in app/views/resources/update.html.erb</p>