config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :businesses do
    resources :resources
    resources :agreements
  end
  resources :users do
    resources :businesses
    resources :resources
    resources :agreements
  end
  resources :resources do
    resources :agreements
  end
  root to: 'welcome#index'
  get ':format', to: 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/agreement.rb
class Agreement < ApplicationRecord
  belongs_to :resource
  belongs_to :business

  #FIXME: need to validate price field.
end

app/controllers/agreements_controller.rb
class AgreementsController < ApplicationController
  before_action :set_user
  before_action :set_business, only: %i[new]
  before_action :set_resource, only: %i[new create]
  before_action :set_agreement, only: %i[new create]
  before_action :set_user_agreement, only: %i[show edit destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @businesses = current_user.businesses.includes(resources: [:agreements])
    @resources = Resource.includes(:agreements).all
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    if @agreement.errors.any?
      render :new
    else
      @agreement = Agreement.create!(agreement_params)
      flash[:notice] = "Successfully added agreement for #{@resource.name}"
      redirect_to user_agreements_path(@user.id)
    end
  end

  def update
  end

  def destroy
  end

  private

  def agreement_params
    params.require(:agreement).permit(
      :price,
      :terms,
      :resource_id,
      :business_id
    )
  end

  def set_user
    if user_signed_in?
      @user = current_user
    else
      puts "======= indexing all agreements for guest user" 
      @user = User.new
    end
    puts "======== agreements_controller:set_user, user_id = #{@user.id}"
  end
  def set_business
    if params[:business_id]
      @business = current_user.businesses.includes(resources: [:agreements]).find(params[:business_id])
    else
      @business = Business.all.includes(:resources).find(Resource.all.find(params[:id]).business_id)
    end
    puts "======== agreements_controller:set_business = #{@business.id}"
  end
  def set_resource
    if params[:resource_id]
      @resource = @business.resources.includes(:agreements).find(params[:resource_id])
      puts "======== agreements_controller:set_resource = #{@resource.id}, business_id = #{@business.id}"
    else
      @resource = Resource.all.includes(:agreements).find(params[:agreement][:id])
      puts "======== agreements_controller:set_resource = #{@resource.id}, business_id = #{@resource.business_id}"
    end
  end
  def set_agreement
    puts "======== agreements_controller:set_agreement, resource_id = #{@resource.id}"
    return unless params[:id]
    @agreement = current_user.agreements.find(params[:id])
  end
  def set_user_agreement
    @agreement = Agreement.find(params[:id])
    @resource = Resource.find(@agreement.resource_id)
  end
end

app/helpers/agreements_helper.rb
module AgreementsHelper
end

app/views/agreements/_agreement_form.html.erb
<div class="home-column-surface">
  <%= form_with model: [ @user, @agreement ], local: true do |form| %>
      <div class="form-input">
        <%= form.label :terms %>
        <%= form.text_area :terms, placeholder: "Room available monday-thursday, 9-5, you'll have to wait for keyfob access if you want to stay later. Don't drink all the milk.", cols: 50, rows: 10 %>
      </div>
      <div class="form-input">
        <%= form.label "Price in dollars per month." %>
        <%= form.text_field :price, placeholder: "$100", size: 55 %>
      </div>
      <%= form.hidden_field :resource_id, value: @resource.id %>
      <%= form.hidden_field :business_id, value: @business.id %>
      <div class="form-input">
        <%= form.submit %>
      </div>
  <% end %>
</div>

app/views/agreements/_agreement_list.html.erb
<div class="home-column-inset full-width-panel left">
  <ul>
    <h2>
      <%= Resource.find(agreement.resource_id).name %>
    </h2>
    <li class="wrap-text">
      <%= "Price: #{agreement.price}" %>
    </li>
    <li class="wrap-text">
      <%= "Contractual terms: #{agreement.terms}" %>
    </li>
    <p>
      <%= link_to "View agreement", user_agreement_path(current_user.id,agreement.id), class: "inlinebutton" %>
      <%= link_to "Delete agreement", user_agreement_path(current_user.id,agreement.id), method: :delete, data: { confirm: "This action will delete this agreement. Are you sure?" }, class: "inlinebutton" %>
    </p>
    </ul>
</div>

app/views/agreements/create.html.erb
<h1>Agreements#create</h1>
<p>Find me in app/views/agreements/create.html.erb</p>

app/views/agreements/destroy.html.erb
<h1>Agreements#destroy</h1>
<p>Find me in app/views/agreements/destroy.html.erb</p>

app/views/agreements/index.html.erb
<%= render 'shared/navbar' %>
<% if @businesses %>
  <% @businesses.each do |b| %>
    <div class="home-column-panel">
      <h1><%= b.name %></h1>
    <% b.resources.each do |r| %>
      <% if r.agreements.count != 0 %>
        <% r.agreements.each do |agg| %>
          <%= render partial: 'agreement_list', locals: {agreement: agg, divclass: "home-column-inset"} %>
        <% end %>
      <% else %>
        <ul>
          <li><%= "currently no agreements for #{r.name}" %></li>
        </ul>
      <% end %>
    <% end %>
    </div>
  <% end %>
<% else %>
  <div class="home-column-panel">
    <h2><%= @user.name %></h2>
    <% if @user.agreements.count != 0 %>
      <% @user.agreements.each do |agg| %>
        <%= render partial: 'agreement_list', locals: {agreement: agg, divclass: "home-column-inset"} %>
      <% end %>
    <% else %>
      <ul>
        <li><%= "currently no agreements for #{@user.name}" %></li>
      </ul>
    <% end %>
  </div>
<% end %>

app/views/agreements/new.html.erb
<%= render 'shared/navbar' %>
<div class="home-column">
  <div class="home-column-panel">
    <h1><% "Lodge your interest in hiring #{@resource.name} from #{@business.name}." %></h1>
    <%= render partial: 'agreement_form', locals: {business: @business, resource: @resource, agreement: @agreement} %>
  </div>
</div>

app/views/agreements/show.html.erb
<%= render 'shared/navbar' %>
<div class="home-column-panel">
  <ul>
    <h1>
      <%= @resource.name %>
    </h1>
    <li class="wrap-text">
      <%= "Price: #{@agreement.price}" %>
    </li>
    <li class="wrap-text">
      <%= "Contractual terms: #{@agreement.terms}" %>
    </li>
    <p>
      <%= link_to "View agreement", user_agreement_path(current_user.id,@agreement.id), class: "inlinebutton" %>
      <%= link_to "Edit agreement", edit_user_agreement_path(current_user.id,@agreement.id), class: "inlinebutton" %>
      <%= link_to "Delete agreement", user_agreement_path(current_user.id,@agreement.id), method: :delete, data: { confirm: "This action will delete this agreement. Are you sure?" }, class: "inlinebutton" %>
    </p>
    </ul>
</div>

app/views/agreements/update.html.erb
<h1>Agreements#update</h1>
<p>Find me in app/views/agreements/update.html.erb</p>